### ISSUE TITLE
Plugin does not work on multi sites

### ISSUE THREAD

**Issue by carrierdown** [tollmanz/custom-taxonomy-sort#1]
I'm using this plugin for a new project, and although it seemed to do everything I need, it's now rendered useless because it will not work on multi sites. It only works on the base site of a multisite, and i can confirm by looking at the wp-tables that only the basic wp_termmeta table is generated, and no similar tables for wp_2_termmeta etc..

Hope this can be fixed soon, if not I will have to roll my own functionality for this. I've created custom meta fields that I use in my theme, and I've gotten this to work nicely in multi sites by using the following code to create the table itself, maybe this is useful to you:

```
$wpdb->product_typesmeta = $wpdb->prefix."product_typesmeta";
$sql = "CREATE TABLE $wpdb->dbname.$wpdb->product_typesmeta (
    meta_id BIGINT( 20 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    product_types_id BIGINT( 20 ) NOT NULL DEFAULT '0',
    meta_key VARCHAR( 255 ) NULL ,
    meta_value LONGTEXT NULL DEFAULT NULL
);";
// dbDelta is not included by default..
require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
dbDelta($sql);
```

-Knut

**Comment by tollmanz** [comment]
@carrierdown Yeah...sorry about that. This plugin fails in many, many ways...ugh. I am making plans to re-write much of the plugin and launch as a version 2. I'm aiming for September to have that done. For now, I'd recommend doing what you need to do to make it work. Things will be different under the hood in the rewrite.

Thanks for stopping by and reporting the issue!

**Comment by carrierdown** [comment]
Alright, thanks for getting back to me. I'll do something else instead then, but it's nice to know that a new version is planned for later projects :) Cheers.
